### ISSUE TITLE
Travis builds fail for node 11

### ISSUE THREAD

**Issue by zWaR** [zWaR/node-inotify#1]
Travis builds are failing for node 11 with the following error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.15.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
```

https://app.travis-ci.com/github/zWaR/node-inotify/jobs/543609175

**Comment by zWaR** [comment]
The reason for failure seems to be related with python version incompatibility. 

When researching possible solutions I stumbled across this https://github.com/firebase/firebase-js-sdk/issues/1352 and gave the downgrade to node version 10 a try. This fixed the issue.

Perhaps configuring TravisCI to run node 11 tests with python2 (and perhaps an older ubuntu version in this case), however this brings up other issues, like if the bindings would work on latest Ubuntu ....

For now I'll close the issue, but feel free to re-open it if you have any better ideas.
